import { useEffect, useState, type JSX } from 'react';
import { Link } from 'react-router-dom';
import { wordFrontMapsApi, type WordFrontBalance, type WordFrontMapDraft, type WordFrontMapDraftList } from '../../../api/word-front-maps';
import styles from './WordFrontMapStudioPage.module.css';

const TOOLS=['.','p','P','#','w','A','S','o'] as const;
export function WordFrontMapStudioPage():JSX.Element{
  const [data,setData]=useState<WordFrontMapDraftList|null>(null),[balance,setBalance]=useState<WordFrontBalance|null>(null),[selected,setSelected]=useState<WordFrontMapDraft|null>(null),[tool,setTool]=useState<(typeof TOOLS)[number]>('.'),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
  useEffect(()=>{const abort=new AbortController();Promise.all([wordFrontMapsApi.list(abort.signal),wordFrontMapsApi.balance(abort.signal)]).then(([value,report])=>{setData(value);setBalance(report);setSelected(value.items[0]??null)}).catch(()=>setError('只有站长账号可打开地图设计台，或服务暂时不可用。'));return()=>abort.abort()},[]);
  const paint=(index:number)=>{if(!selected)return;const row=Math.floor(index/8),col=index%8,cells=[...selected.cells];cells[row]=cells[row]!.slice(0,col)+tool+cells[row]!.slice(col+1);setSelected({...selected,cells});setNotice(null)};
  const save=async()=>{if(!selected||busy)return;setBusy(true);setError(null);try{const next=await wordFrontMapsApi.save(selected.key,{name:selected.name,cells:selected.cells,expectedVersion:selected.version});setSelected(next);setData(value=>value?{...value,items:value.items.map(item=>item.key===next.key?next:item)}:value);setNotice(`草稿已保存为 v${next.version}。排行榜地图不会被静默改写，需随规则版本发布。`)}catch{setError('保存失败：请检查两组阿斗/出兵口、双方兵道数量，或刷新处理版本冲突。')}finally{setBusy(false)}};
  return <main className={styles.page}><header><div><span>ADMIN / MAP STUDIO</span><h1>赵云救阿斗 · 地图设计台</h1><p>编辑 8×10 地图草稿，并用最近 30 天真实验真对局观察地图平衡。</p></div><nav><Link to="/tower-defense/word-front">返回战役</Link><Link to="/development">开发协作</Link></nav></header>{error?<p role="alert" className={styles.error}>{error}</p>:null}{notice?<p role="status" className={styles.notice}>{notice}</p>:null}{balance?<section aria-label="30天平衡观测"><h2>30 天平衡观测</h2><p>{balance.rows.length?balance.rows.map(row=>`地图${row.map??'无尽'} ${row.outcome==='won'?'胜':'负'} ${row.runs}局 / 平均${row.averageWave??'—'}波`).join(' · '):'还没有足够的 V4 验真样本；上线后会自动累计，不用人工填表。'}</p></section>:null}{selected&&data?<div className={styles.layout}><aside><h2>地图草稿</h2>{data.items.map(item=><button key={item.key} data-active={selected.key===item.key} onClick={()=>{setSelected(item);setNotice(null)}}>{item.name}<small>{item.key} · v{item.version}</small></button>)}</aside><section><div className={styles.meta}><label>名称<input value={selected.name} maxLength={64} onChange={event=>setSelected({...selected,name:event.target.value})}/></label><span>最后保存 {new Date(selected.updatedAt).toLocaleString('zh-CN')}</span></div><div className={styles.tools} role="group" aria-label="地图画笔">{TOOLS.map(value=><button key={value} aria-pressed={tool===value} data-active={tool===value} onClick={()=>setTool(value)}><b>{value}</b><small>{data.symbols[value]}</small></button>)}</div><div className={styles.board} role="grid" aria-label="地图草稿网格">{selected.cells.flatMap((row,rowIndex)=>[...row].map((value,colIndex)=><button role="gridcell" key={`${rowIndex}-${colIndex}`} data-cell={value} aria-label={`${rowIndex+1}行${colIndex+1}列，${data.symbols[value]??value}`} onClick={()=>paint(rowIndex*8+colIndex)}>{value}</button>))}</div><div className={styles.actions}><button disabled={busy||!selected.name.trim()} onClick={()=>void save()}>{busy?'保存中…':'保存草稿'}</button><button disabled={busy} onClick={()=>setSelected(data.items.find(item=>item.key===selected.key)??selected)}>放弃未保存修改</button></div><p className={styles.help}>约束：10 行 × 8 列；A 与 S 各两个；己方 p、对方 P 兵道各至少 8 格。正式启用仍需版本化引擎、测试与部署，避免旧成绩失去可复算性。</p></section></div>:!error?<p role="status">正在载入地图…</p>:null}</main>;
}
