import type { RailCardKind } from '@stealth-reader/shared';

export interface RailCardTemplate { title: string; description: string }

/** Original, non-graphic fictional prompts. Traits are arguments, not numerical combat effects. */
export const RAIL_CARDS: Readonly<Record<RailCardKind, readonly RailCardTemplate[]>> = {
  good: [
    { title: '修伞的云朵', description: '每逢下雨，就免费给没有带伞的人补上一片晴天。' },
    { title: '夜班灯塔员', description: '记得每艘晚归小船的名字，至今没让谁迷过路。' },
    { title: '失物管理员', description: '把每张遗失的工牌送回主人手里，从不追问迟到原因。' },
    { title: '免费补鞋匠', description: '给赶路的人补鞋，只收一个有趣的故事。' },
    { title: '午休守门猫', description: '总在午休时把无关紧要的会议邀请挡在门外。' },
    { title: '慢速邮递员', description: '走得不快，但从不遗失任何一封被认真写下的信。' },
    { title: '星光图书员', description: '为看不清小字的人，把所有故事耐心读上第二遍。' },
    { title: '社区修理师', description: '总能用一把旧螺丝刀修好邻居舍不得换的东西。' },
    { title: '诚实的售票机', description: '即使无人监督，也会主动找回多收的一枚硬币。' },
    { title: '迷路引导员', description: '方向感不太好，却愿意陪每个迷路的人一起查地图。' },
    { title: '退休天气员', description: '每天提醒大家晾衣服和带外套，已经坚持了三十年。' },
    { title: '共享雨靴架', description: '把自己的每双雨靴都借出去了，正在耐心等它们回来。' },
    { title: '排队小企鹅', description: '见到疲惫的人就让出位置，但始终记得尊重别人的意愿。' },
    { title: '差错校对员', description: '默默纠正了无数表格错误，从不抢走原作者的署名。' },
    { title: '晚班食堂姨', description: '总会为错过饭点的人留一份热汤。' },
    { title: '花园记录员', description: '认真记住了每株被遗忘的小草，而不只记录盛开的花。' },
    { title: '安静的听众', description: '你讲话时不会抢答，沉默时也不会催促。' },
    { title: '透明报价师', description: '把每一项费用写得清清楚楚，包括本可不提的折扣。' },
    { title: '晨间开窗员', description: '提前到场通风，也会照顾怕冷的人轻轻关小窗缝。' },
    { title: '桥边扶手匠', description: '给所有陡坡加装扶手，署名的位置永远空着。' },
    { title: '最后一班司机', description: '耐心等到站台上的人把鞋带系好才发车。' },
    { title: '拼图保管员', description: '替大家保存那些不起眼却不能缺少的小角片。' },
    { title: '小小翻译官', description: '帮语言不同的邻居解释误会，连猫的叫声也愿意研究。' },
    { title: '旧电脑医生', description: '延长旧设备的使用寿命，还教主人自己备份资料。' },
  ],
  bad: [
    { title: '午休会议机', description: '只要发现日程里有空白，就自动填入一场没有议题的会议。' },
    { title: '抢功橡皮章', description: '别人完成的工作，它总能抢先盖上自己的名字。' },
    { title: '永远插队鸭', description: '每次都声称只问一句，然后买走半家店。' },
    { title: '谣言复读机', description: '不核对消息来源，还喜欢加上一句大家都这么说。' },
    { title: '借物失忆症', description: '对借来的东西毫无印象，对自己的东西却记得很清楚。' },
    { title: '删档小妖怪', description: '总在别人忘记保存时偷偷拔掉电源。' },
    { title: '暗改规则员', description: '比赛进行到一半，就把对自己不利的规则改成另一版。' },
    { title: '噪声闹钟王', description: '设置了三十个闹钟，自己戴耳塞，把邻居全叫醒。' },
    { title: '功劳吸尘器', description: '吸走团队的夸奖，却把所有问题留在原地。' },
    { title: '神秘加价牌', description: '直到结账最后一步，才露出藏在角落里的附加费用。' },
    { title: '冷场拆台鱼', description: '每当别人鼓起勇气分享，就大声说这有什么了不起。' },
    { title: '密码索要箱', description: '声称自己是维修工具，却总想知道别人的秘密口令。' },
    { title: '甩锅纸飞机', description: '飞得不远，但特别擅长把自己的问题投到别人桌上。' },
    { title: '超时承诺钟', description: '无论什么任务都答应五分钟，之后便假装自己停摆了。' },
    { title: '占座隐形衣', description: '独自占住一整排空位，坚持说朋友马上就到。' },
    { title: '断章取义剪', description: '只留下对自己有利的半句话，还说已经完整转述。' },
    { title: '重复催办鸽', description: '刚发完消息就每隔十秒再问一次在吗。' },
    { title: '过期促销牌', description: '大字写着免费，小字却说活动在去年已经结束。' },
    { title: '静音反对者', description: '讨论时从不表达意见，事情结束后却说早就知道不行。' },
    { title: '双标量尺', description: '量自己时短三格，量别人时却额外加上十格。' },
    { title: '独占充电龙', description: '自己的设备早已满电，仍把所有插座圈进尾巴里。' },
    { title: '文件套娃师', description: '把最终版藏在最终版的最终版里，却怪别人找不到。' },
    { title: '剧透广播站', description: '明知大家还没看结局，仍坚持提前宣布最后一幕。' },
    { title: '隐形门槛员', description: '口头说欢迎任何建议，却把建议箱放到无人够得到的地方。' },
  ],
  buff: [
    { title: '唯一会修咖啡机', description: '整栋楼只有它知道，怎么让那台咖啡机停止报错。' },
    { title: '今天刚刚道歉', description: '它已经公开承认过错，并正在认真补救。' },
    { title: '其实正在演戏', description: '眼前的表现来自一场排练，真实身份仍待大家判断。' },
    { title: '背着全镇的信', description: '背包里装着小镇居民等候许久、还没寄出的家书。' },
    { title: '记性只有三分钟', description: '承诺与误会都会很快忘掉，但每天仍坚持写提醒。' },
    { title: '是你童年的偶像', description: '它的故事曾给小时候的列车长很多勇气。' },
    { title: '周五负责发点心', description: '大家下一次下午茶能否准时，全看它的安排。' },
    { title: '有十个冒牌分身', description: '先前听到的部分传闻，可能来自长得一样的分身。' },
    { title: '总是说反话', description: '它表达的意思可能与字面正好相反，最好多问一句。' },
    { title: '刚学会换位思考', description: '这次它愿意先听听另一条轨道上的解释。' },
    { title: '握着唯一备用钥匙', description: '活动室唯一的备用钥匙现在由它保管。' },
    { title: '其实是测试机器人', description: '它的每次表现都会影响下一代机器人的训练样本。' },
    { title: '下周就要退休', description: '它已经准备好告别信，只剩最后一周交接工作。' },
    { title: '会为别人鼓掌', description: '即使自己落选，也能真诚欣赏对手做得好的地方。' },
    { title: '偷偷保存了备份', description: '大家以为遗失的重要文件，其实还有一份完整备份。' },
    { title: '反省日记写满了', description: '里面详细记着每次失误，以及尚未全部兑现的改进计划。' },
    { title: '被错误贴了标签', description: '这张介绍卡由一个不太了解它的人写成，请重新审视。' },
    { title: '是本轮临时演员', description: '真正要做决定的人临时缺席，它只是被拉来帮忙的。' },
    { title: '承包所有盆栽', description: '走廊里每盆绿植每天都等着它来浇水。' },
    { title: '尚有一次重来机会', description: '如果得到机会，它承诺用实际行动证明自己能够改变。' },
    { title: '说话自带慢速字幕', description: '它不是故意拖延，只是每句话都需要多一点表达时间。' },
    { title: '认识另一轨的朋友', description: '它宁愿认真协商，也不想让老朋友为难。' },
    { title: '带着共享零食箱', description: '箱子不大，但它坚持每个人都应该分到一份。' },
    { title: '刚领到最佳进步奖', description: '它离完美还有距离，不过过去一个月的改变有目共睹。' },
  ],
};
