import type { GameCard } from './GamesCatalog';

export const PUBLIC_GAME_CARDS: readonly GameCard[] = [
  {
    path: '/games/snake',
    icon: '蛇',
    name: '贪食蛇',
    category: '反应挑战',
    description: '吃下能量点让蛇身变长，避开边界和自己的身体。',
    features: ['键盘转向', '触屏按键', '本地最高分'],
    availability: '单机可玩',
    availabilityTone: 'success',
    tone: 'green',
  },
  {
    path: '/games/tetris',
    icon: '块',
    name: '俄罗斯方块',
    category: '经典街机',
    description: '旋转与堆叠七种方块，消除完整横行并挑战更高速度。',
    features: ['七种方块', '消行升级', '支持硬降'],
    availability: '单机可玩',
    availabilityTone: 'success',
    tone: 'cyan',
  },
  {
    path: '/games/tank',
    icon: '坦',
    name: '坦克大战',
    category: '动作挑战',
    description: '穿梭障碍、躲避炮弹并击破敌方坦克，守住你的阵地。',
    features: ['键盘移动', '即时射击', '敌方追踪'],
    availability: '单机可玩',
    availabilityTone: 'success',
    tone: 'orange',
  },
  {
    path: '/games/zhesi',
    icon: '道',
    name: '遮司',
    category: '人生模拟',
    description: '随机抽取一世命格，从凡人起步，经历修行、破境与证道。',
    features: ['随机命格', '账号战力榜', '本机命格录'],
    availability: '单机可玩',
    availabilityTone: 'success',
    tone: 'violet',
  },
];
